apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: restaurant.migrations
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "2592000000"     # 30 days (migration audit trail)
    cleanup.policy: delete
    segment.bytes: "104857600"
